### ISSUE TITLE
Проблемы установки глобальных модулей для macOS, Linux, Ubuntu

### ISSUE THREAD

**Issue by Thr0TT1e** [solversgroup/marmelad#71]
При установке через npm (глобально) выдаёт следующую ошибку:
```
npm i marmelad -g
Password:
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
/usr/local/bin/marmelad -> /usr/local/lib/node_modules/marmelad/bin/marmelad.js
/usr/local/bin/mmd -> /usr/local/lib/node_modules/marmelad/bin/marmelad.js

> fsevents@1.2.11 install /usr/local/lib/node_modules/marmelad/node_modules/fsevents
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/ThreeT/Library/Caches/node-gyp/12.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/marmelad/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/marmelad/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/marmelad/node_modules/fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> node-sass@4.13.0 install /usr/local/lib/node_modules/marmelad/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/local/lib/node_modules/marmelad/node_modules/node-sass/vendor/darwin-x64-72 : Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/marmelad/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:823:3)
    at sync (/usr/local/lib/node_modules/marmelad/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/marmelad/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/local/lib/node_modules/marmelad/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/marmelad/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/marmelad/node_modules/node-sass/vendor'
}

> phantomjs-prebuilt@2.1.16 install /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1576996968766/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN svg-spritemap-webpack-plugin@2.7.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/marmelad/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ThreeT/.npm/_logs/2019-12-22T06_42_54_380Z-debug.log
```

Однако, на Windows всё установилось.
Утилиты:
```
npm -v
6.13.4
```

```
node -v
v12.14.0
```

**Comment by Thr0TT1e** [comment]
Windows 10
При запуске на указанной ОС выдаёт следующие сообщения:
```
$ marmelad dev
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'Y:\Cloud\G.Drive\Project\! learn\marmelad\marmelad/marmelad/settings.marmelad'
Require stack:
- C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\commands\dev.js
- C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\bin\marmelad.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\commands\dev.js:79:20)
    at Command.<anonymous> (C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\bin\marmelad.js:44:31)
    at Command.listener (C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\ThreeT\AppData\Roaming\npm\node_modules\marmelad\node_modules\commander\index.js:474:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\ThreeT\\AppData\\Roaming\\npm\\node_modules\\marmelad\\commands\\dev.js',
    'C:\\Users\\ThreeT\\AppData\\Roaming\\npm\\node_modules\\marmelad\\bin\\marmelad.js'
  ]
}
```

**Comment by yunusga** [comment]
[Mac Os](https://github.com/solversgroup/marmelad/issues/71#issue-541420748) давно не тестировал - буду проверять
[Win 10](https://github.com/solversgroup/marmelad/issues/71#issuecomment-568294330) - довольно странно, в основном на Win 10 и работает сборка. Думаю дело может быть в спецсимволах в пути до проекта `! learn` (надо проверить)

Как выход, советую воспользоваться [установкой для разработчиков](https://github.com/solversgroup/marmelad/tree/develop#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2) из ветки [develop](https://github.com/solversgroup/marmelad/tree/develop).

Сейчас работаю над выпиливанием PhantomJS из зависимостей + много оптимизаций и переделок. К концу года будет релиз новой версии, скорее всего она будет частично не совместима с проектами прошлых версий.

**Comment by Thr0TT1e** [comment]
Поправил путь, удалил `.` и `!` и всё заработало. Но вот одна проблема, например, фалы размещаю на облачном диске для доступа с разных компьютеров, а у них присутствует (обычно) точка в наименовании (((

**Comment by yunusga** [comment]
@Thr0TT1e Думаю тут дело было именно в !

**Comment by Thr0TT1e** [comment]
`!` удалил, попытался запустить ошибка как выше, путь стал - `Y:\Cloud\G.Drive\Project\learn\marmelad\marmelad/marmelad/settings.marmelad`

Убрал символ точки и всё запустилось.

**Comment by yunusga** [comment]
@Thr0TT1e по MacOs ошибка `code: 'EACCES'` необходимо устанавливать с `sudo npm i marmelad -g`

**Comment by yunusga** [comment]
@Thr0TT1e протестировал с разными путями `Projects\G.Drive\Project\learn\! marmelad stock`, всё работает.

Разобрался в чём проблема, не был [инициализирован новый проект](https://github.com/solversgroup/marmelad/tree/develop#init-options-%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F). Ознакомься с [Marmelad CLI](https://github.com/solversgroup/marmelad/tree/develop#marmelad-cli)

**Comment by Thr0TT1e** [comment]
> @Thr0TT1e по MacOs ошибка `code: 'EACCES'` необходимо устанавливать с `sudo npm i marmelad -g`

```
  ~/frontend_work  sudo npm i marmelad -g
Password:
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
/usr/local/bin/mmd -> /usr/local/lib/node_modules/marmelad/bin/marmelad.js
/usr/local/bin/marmelad -> /usr/local/lib/node_modules/marmelad/bin/marmelad.js

> fsevents@1.2.11 install /usr/local/lib/node_modules/marmelad/node_modules/fsevents
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/ThreeT/Library/Caches/node-gyp/12.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/marmelad/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/marmelad/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/marmelad/node_modules/fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> node-sass@4.13.0 install /usr/local/lib/node_modules/marmelad/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/local/lib/node_modules/marmelad/node_modules/node-sass/vendor/darwin-x64-72 : Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/marmelad/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:823:3)
    at sync (/usr/local/lib/node_modules/marmelad/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/marmelad/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/local/lib/node_modules/marmelad/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/marmelad/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/marmelad/node_modules/node-sass/vendor'
}

> phantomjs-prebuilt@2.1.16 install /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1577200821238/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/local/lib/node_modules/marmelad/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/marmelad/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ThreeT/.npm/_logs/2019-12-24T15_20_27_133Z-debug.log
```

**Comment by yunusga** [comment]
Mac is какой версии?

**Comment by yunusga** [comment]
@Thr0TT1e 

По умолчанию npm устанавливает пакеты локально в ваших проектах. Вы также можете установить установочные пакеты глобально (например, npm install -g <package>) (полезно для приложений командной строки). Однако недостатком этого является то, что вам нужно получить root-права (или использовать sudo) для возможности глобальной установки.

Ознакомьтесь с руководством NPM для установки глобальных модулей [Resolving EACCES permissions errors when installing packages globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

```bash
Developers-Mac:~ developer$ npm i marmelad -g
...
+ marmelad@7.0.0
added 1559 packages from 1261 contributors in 920.659s


Developers-Mac:~ developer$ mmd --help
Usage: mmd [options] [command]

Заготовка фронтенд проекта для продвинутых и начинающих 🤘

Options:
  -v, --version          output the version number
  -h, --help             output usage information

Commands:
  init [options] [dir]   initialize new project
  dev [options]          run development server
  cp <name>              create new page
  cb [options] <name>    create new block
  lint                   lint project
  dist                   Release tasks for project
  pack [options] [name]  Archive project source code (default:tar.gz)

Commands help:
  marmelad [command] --help
  mmd [command] --help

Source files:
  /Users/developer/.npm-global/lib/node_modules/marmelad/bin/marmelad.js
```

**Comment by Thr0TT1e** [comment]
> Mac is какой версии?

MacOS Catalina 10.15.2

**Comment by yunusga** [comment]
@Thr0TT1e В последнем комменте описал решение проблемы с установкой глобальных модулей.
